name: Deploy Next.js site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build static Next.js site
        run: |
          npm run build
          npm run export

      - name: Build Sanity Studio
        working-directory: ./studio
        run: |
          npm ci
          npm run build

      - name: Copy Studio to `out/studio` and fix asset paths
        run: |
          mkdir -p out/studio
          cp -r studio/dist/* out/studio/

          # Patch asset paths in index.html
          sed -i 's|/static/|/studio/static/|g' out/studio/index.html
          sed -i 's|/vendor/|/studio/vendor/|g' out/studio/index.html
          sed -i 's|"/vendor/|"/studio/vendor/|g' out/studio/index.html

          # Patch basePath in generated JS
          sanity_js=$(find out/studio/static -name "sanity-*.js" | head -n 1)
          sed -i 's|basePath:"/"|basePath:"/studio"|g' "$sanity_js"

          # Fix for GitHub Pages
          touch out/.nojekyll

      - name: Upload `out/` to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
